### ISSUE TITLE
Zrythm does not recognise DROPS as a LV2 Plugin

### ISSUE THREAD

**Issue by ghost** [clearly-broken-software/drops#13]
So, I tried using DROPS as a plugin in Zrythm and Zrythm did not recognise it as a LV2 plugin. It threw this error:
![zrythm_ClcmwmTpg5](https://user-images.githubusercontent.com/37266538/99559014-ff67ec00-29cc-11eb-9896-4908b0b54543.png)

**Comment by rghvdberg** [comment]
For now it's only compiled for Linux

Op wo 18 nov. 2020 17:37 schreef MrTeeXD <notifications@github.com>:

**Comment by ghost** [comment]
Any ETA for Windows? I could really use a Plugin like this

**Comment by rghvdberg** [comment]
Erm... No. No idea

**Comment by rghvdberg** [comment]
I'm closing this ;-)
