### ISSUE TITLE
Support for opus audio-format

### ISSUE THREAD

**Issue by Porrumentzio** [clearly-broken-software/drops#26]

**Comment by rghvdberg** [comment]
I'll check if sfizz can use opus

**Comment by rghvdberg** [comment]
Drops uses libsndfile for loading audio files. You need libsndfile 1.0.29 or higher to load opus.

libsndfile docs state : `From version 1.0.29, libsndfile can read and write Ogg/Opus.`.
Version [1.0.29 ](https://github.com/libsndfile/libsndfile/releases/tag/v1.0.29) was released on 15 Aug 2020.
[Github Actions CI ](https://github.com/actions/virtual-environments) uses "ubuntu-latest" which is 18.04, so if you use the binaries from github you are out of luck :-/.
