### ISSUE TITLE
Compile fails

### ISSUE THREAD

**Issue by AVLinux** [clearly-broken-software/drops#40]
Hi,

Trying to build DROPS from github source on AV Linux MX Edition (based on Debian Buster) and having issues..

Issue 1:  Repository clones without submodules and no documented instruction that git submodule commands are needed to fetch all the required sources. 'git clone --recursive' doesn't fetch everything. So I ran the submodule init and updated them but then encountered build errors.

Issue 2: Build fails with this message:

```
$ make
make -C dpf/dgl
make[1]: Entering directory '/media/DATA1/Packaging/DROPS/drops/dpf/dgl'
Compiling src/Application.cpp
Compiling src/Color.cpp
Compiling src/Geometry.cpp
Compiling src/ImageBase.cpp
Compiling src/Resources.cpp
Compiling src/Widget.cpp
Compiling src/Cairo.cpp (Cairo variant)
Compiling src/WidgetPrivateData.cpp (Cairo variant)
Compiling src/Window.cpp (Cairo variant)
Creating libdgl-cairo.a
Compiling src/OpenGL.cpp (OpenGL variant)
Compiling src/Image.cpp (OpenGL variant)
Compiling src/ImageWidgets.cpp (OpenGL variant)
Compiling src/NanoVG.cpp (OpenGL variant)
Compiling src/WidgetPrivateData.cpp (OpenGL variant)
Compiling src/Window.cpp (OpenGL variant)
Creating libdgl-opengl.a
Symlinking libdgl.a
make[1]: Leaving directory '/media/DATA1/Packaging/DROPS/drops/dpf/dgl'
Compiling /media/DATA1/Packaging/DROPS/drops/sfizz//src/sfizz/ADSREnvelope.cpp
In file included from /media/DATA1/Packaging/DROPS/drops/sfizz//src/sfizz/SfzHelpers.h:8,
                 from /media/DATA1/Packaging/DROPS/drops/sfizz//src/sfizz/CCMap.h:8,
                 from /media/DATA1/Packaging/DROPS/drops/sfizz//src/sfizz/Region.h:8,
                 from /media/DATA1/Packaging/DROPS/drops/sfizz//src/sfizz/ADSREnvelope.h:8,
                 from /media/DATA1/Packaging/DROPS/drops/sfizz//src/sfizz/ADSREnvelope.cpp:7:
/media/DATA1/Packaging/DROPS/drops/sfizz//src/sfizz/Config.h:15:10: fatal error: absl/strings/string_view.h: No such file or directory
 #include "absl/strings/string_view.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [sfizz/dpf.mk:83: /media/DATA1/Packaging/DROPS/drops/sfizz//dpf-build/src/sfizz/ADSREnvelope.cpp.o] Error 1

```

**Comment by rghvdberg** [comment]
mmm
that's abseil submodule missing, somehow

I'll have a look tomorrow, see if I can replicate

**Comment by AVLinux** [comment]
Thanks!!

**Comment by rghvdberg** [comment]
actually, I just tried it and everything works as described in the readme ¯\\_(ツ)_/¯

**Comment by AVLinux** [comment]
Ok, I think I know what happened...

If you've just heard about DROPS and you're so excited that you just go straight to the 'Code' button on ye olde Github page you get this:

git clone https://github.com/clearly-broken-software/drops.git

So no recursey you just get drops without subbies! If you then re-run the command with --recursive for some reason it doesn't pull in the submodules to the original git repo you just cloned on your computer and apparently manually running init and update also doesn't quite get the job done like it should..

So the moral of the story is... don't ever get excited about anything...EVER! And never just clone a git repo without scrolling down and reading the instructions slowly and carefully. I will declare this closed and NEVER speak again....*blushes
